/**
 * Visual Rendering Constants
 *
 * Centralized configuration for all visual rendering parameters in VisualMapRenderer.
 * Extracted from magic numbers to improve maintainability and tunability.
 */

// ============================================================================
// LAYER Z-INDICES
// ============================================================================
export const LAYER_INDICES = {
  MAP_BACKGROUND: 0,
  PATH: 1,
  CORPSES: 2,
  DECAL_ANIMATIONS: 3,
  CAMP_ANIMATIONS: 4,
  FOG: 5,
} as const;

// ============================================================================
// COLORS
// ============================================================================
export const COLORS = {
  // Ground colors - layered desolate olive / ash / mud
  GROUND_BASE: 0x2a3820,
  GROUND_MOTTLE_DARK: 0x1f2c18,
  GROUND_MOTTLE_LIGHT: 0x354828,
  GROUND_DIRT_PATCH: 0x3d4d32,
  GROUND_DIRT_CORE: 0x455538,
  GROUND_DEAD_GRASS: 0x4a5a3f,
  GROUND_DEAD_GRASS_TIP: 0x5a6a4a,
  GROUND_BARREN_DIRT: 0x5a4a3f,
  GROUND_MUD: 0x4a3a2a,
  GROUND_ASH: 0x4a4a3a,
  GROUND_ROCK: 0x4a4a4a,
  GROUND_ROCK_HIGHLIGHT: 0x6a6a6a,
  GROUND_ROCK_SHADOW: 0x2a2a2a,
  GROUND_PEBBLE: 0x5a5a5a,
  GROUND_CRACK: 0x1a1a12,
  GROUND_CRACK_EDGE: 0x2a2a1a,
  GROUND_STAIN: 0x1f2f15,
  GROUND_STAIN_DARK: 0x151f10,
  GROUND_GRASS_TUFT: 0x3d4d32,

  // UI colors
  UI_PANEL_BG: 0x2a2a2a,
  UI_SEPARATOR: 0x654321,

  // Path colors - layered worn dirt road
  PATH_SHOULDER: 0x3a4a2a, // Soft grass/dirt blend at edges
  PATH_OUTER: 0x2e2218, // Dark packed border
  PATH_DIRT: 0x5c4a3a, // Main worn dirt
  PATH_DIRT_LIGHT: 0x6e5a48, // Sun-bleached / scuffed patches
  PATH_INNER: 0x4a3a2c, // Packed center rut bed
  PATH_TRACK: 0x3a2c20, // Deep cart/rut lines
  PATH_ROCK: 0x6a6a6a,
  PATH_ROCK_SHADOW: 0x2a2a2a,
  PATH_FOOTPRINT: 0x2d1f12,
  PATH_MUD: 0x4a3828,
  PATH_CRACK: 0x1f1610,
  PATH_HIGHLIGHT: 0x7a6a58, // Soft edge scuff

  // Tree colors
  TREE_TRUNK: 0x4a3a2a,
  TREE_TRUNK_OUTLINE: 0x2a1a1a,
  TREE_BARK: 0x3a2a1a,
  TREE_BRANCH: 0x4a3a2a,
  TREE_PINE_TRUNK: 0x5a4a3a,
  TREE_PINE_FOLIAGE: 0x2a4a2a,
  TREE_PINE_FOLIAGE_OUTLINE: 0x1a3a1a,
  TREE_PINE_DETAIL: 0x1a3a1a,

  // Graveyard colors
  GRAVEYARD_GRASS: 0x2a3a2a,
  GRAVEYARD_EARTH: 0x4a3a2a,
  GRAVEYARD_BONE: 0xf5f5dc,
  GRAVEYARD_STAIN: 0x1a1a1a,
  GRAVEYARD_FENCE_IRON: 0x6a4513,
  GRAVEYARD_FENCE_OUTLINE: 0x4a3013,
  GRAVEYARD_RUST: 0x8b4513,
  GRAVEYARD_FENCE_POST: 0x5a4321,
  GRAVEYARD_POST_OUTLINE: 0x3a2a11,
  GRAVEYARD_WOOD_GRAIN: 0x4a3211,
  GRAVEYARD_GATE_PILLAR: 0x5a5a5a,
  GRAVEYARD_GATE_PILLAR_OUTLINE: 0x3a3a3a,
  GRAVEYARD_GATE_CRACK: 0x2a2a2a,
  GRAVEYARD_MOSS: 0x2a4a2a,
  GRAVEYARD_SKULL: 0xe5e5cc,
  GRAVEYARD_SKULL_OUTLINE: 0xc5c5ac,
  GRAVEYARD_SKULL_FEATURE: 0x1a1a1a,
  GRAVEYARD_GATE_METAL: 0x5a4a3a,
  GRAVEYARD_GATE_OUTLINE: 0x3a2a1a,
  GRAVEYARD_SIGN: 0x3a2a1a,
  GRAVEYARD_SIGN_OUTLINE: 0x2a1a0a,
  GRAVEYARD_CHAIN: 0x5a4a3a,
  GRAVEYARD_CHAIN_LINK: 0x3a2a1a,

  // Ruined house colors
  HOUSE_WALL: 0xa0826d,
  HOUSE_WALL_BACK: 0x6b5d4f,
  HOUSE_WALL_SIDE: 0x8b7355,
  HOUSE_WALL_TOWNHOUSE: 0x7a6a5a,
  HOUSE_WALL_OUTLINE: 0x654321,
  HOUSE_FOUNDATION: 0x5a5a5a,
  HOUSE_FOUNDATION_OUTLINE: 0x3a3a3a,
  HOUSE_INTERIOR: 0x2a2218,
  HOUSE_ROOF: 0x8b4513,
  HOUSE_ROOF_FARM: 0x7a4a3a,
  HOUSE_ROOF_BEAM: 0x5a3a2a,
  HOUSE_CHIMNEY: 0x6a5a4a,
  HOUSE_CHIMNEY_SOOT: 0x2a2a2a,
  HOUSE_WINDOW: 0x1a1a1a,
  HOUSE_WINDOW_FRAME: 0x654321,
  HOUSE_WINDOW_GLASS: 0x6a8a9a,
  HOUSE_DOOR_FRAME: 0x4a3a2a,
  HOUSE_DOOR: 0x654321,
  HOUSE_DOOR_PLANK: 0x5a4a3a,
  HOUSE_RUBBLE: 0x8b7355,
  HOUSE_RUBBLE_DARK: 0x5a5a5a,
  HOUSE_RUBBLE_MID: 0x7a6a5a,
  HOUSE_BURN_MARK: 0x1a1a1a,
  HOUSE_SMOKE: 0x808080,
  HOUSE_CRACK: 0x2a2a2a,
  HOUSE_MOSS: 0x3a5a3a,
  HOUSE_SHADOW: 0x000000,
  HOUSE_BRICK_LINE: 0x8a7a6a,

  // Decoration colors
  DECOR_DEAD_BUSH: 0x4a3a2a,
  DECOR_ROCK: 0x6a6a6a,
  DECOR_ROCK_OUTLINE: 0x4a4a4a,
  DECOR_STUMP: 0x5a4a3a,
  DECOR_GRASS_PATCH: 0x3a4a2a,
  DECOR_SKULL: 0xf5f5dc,
  DECOR_EYE_SOCKET: 0x1a1a1a,

  // Camp colors
  CAMP_GROUND: 0x4a3a2a,
  CAMP_FOOTPRINT: 0x3a2a1a,
  CAMP_FENCE: 0x5a5a5a,
  CAMP_FENCE_OUTLINE: 0x3a3a3a,
  CAMP_FENCE_BAR: 0x4a4a4a,
  CAMP_GATE: 0x7a7a7a,
  CAMP_GATE_OUTLINE: 0x5a5a5a,
  CAMP_TENT_BASE: 0x6b7c3a,
  CAMP_TENT_OUTLINE: 0x4a5a2a,
  CAMP_TENT_ROOF: 0x5a6a2a,
  CAMP_TENT_ROOF_OUTLINE: 0x3a4a1a,
  CAMP_TENT_PATCH: 0x4a4a4a,
  CAMP_TENT_FLAP: 0x4a5a2a,
  CAMP_ROPE: 0x654321,
  CAMP_STAKE: 0x654321,
  CAMP_MEDICAL_TENT_ROOF: 0xe5e5cc,
  CAMP_MEDICAL_TENT_OUTLINE: 0xc5c5ac,
  CAMP_MEDICAL_TENT_WALL: 0xf5f5dc,
  CAMP_RED_CROSS: 0xcc0000,
  CAMP_SUPPLY_TENT_ROOF: 0x8b7355,
  CAMP_SUPPLY_TENT_OUTLINE: 0x654321,
  CAMP_SUPPLY_TENT_WALL: 0xa0826d,
  CAMP_SANDBAG: 0x8b7355,
  CAMP_SANDBAG_OUTLINE: 0x654321,
  CAMP_CRATE: 0x8b7355,
  CAMP_CRATE_OUTLINE: 0x654321,
  CAMP_CRATE_BAND: 0x4a4a4a,
  CAMP_WATCHTOWER_WOOD: 0x654321,
  CAMP_WATCHTOWER_PLATFORM: 0x8b7355,
  CAMP_WATCHTOWER_RAILING: 0x654321,
  CAMP_RADIO_ANTENNA: 0x4a4a4a,
  CAMP_RADIO_LIGHT: 0xff0000,
  CAMP_FIRE_RING_STONE: 0x5a5a5a,
  CAMP_FIRE_RING_OUTLINE: 0x3a3a3a,
  CAMP_FIRE_PIT: 0x2a2a2a,
  CAMP_LOG: 0x654321,
  CAMP_LOG_OUTLINE: 0x4a3211,
  CAMP_CLOTHESLINE: 0x3a3a3a,
  CAMP_CLOTHES_BLUE: 0x4169e1,
  CAMP_CLOTHES_GREEN: 0x228b22,
  CAMP_SIGN: 0x8b7355,
  CAMP_SIGN_OUTLINE: 0x654321,
  CAMP_SIGN_STRIPE: 0xffcc00,
  CAMP_SIGN_SAFE_ZONE: 0x00aa00,
  CAMP_SIGN_SAFE_ZONE_OUTLINE: 0x008800,
  CAMP_SIGN_NAIL: 0x4a4a4a,
  CAMP_GENERATOR: 0x6a6a6a,
  CAMP_GENERATOR_OUTLINE: 0x4a4a4a,
  CAMP_GENERATOR_EXHAUST: 0x2a2a2a,
  CAMP_FUEL_CAN: 0xcc0000,
  CAMP_FUEL_CAN_OUTLINE: 0xaa0000,
  CAMP_TABLE: 0x8b7355,
  CAMP_TABLE_LEG: 0x654321,
  CAMP_CUP: 0x4a6a8a,
  CAMP_BOOK: 0x8b4513,
  CAMP_LIGHT_BULB: 0xffaa00,
  CAMP_BACKPACK: 0x3a4a2a,
  CAMP_BACKPACK_OUTLINE: 0x2a3a1a,
  CAMP_BOOTS: 0x4a3a2a,
  CAMP_GUITAR_BODY: 0x8b7355,
  CAMP_GUITAR_NECK: 0x654321,
  CAMP_MEMORIAL_CROSS: 0x8b7355,
  CAMP_FLOWER_RED: 0xff6666,
  CAMP_FLOWER_YELLOW: 0xffff66,

  // Fire colors
  FIRE_OUTER: 0xff4500,
  FIRE_MIDDLE: 0xffa500,
  FIRE_INNER: 0xffff00,
  FIRE_CORE: 0xffffaa,

  // Survivor colors
  SURVIVOR_SKIN: 0xffdbac,
  SURVIVOR_BROWN_CLOTHES: 0x654321,
  SURVIVOR_BLUE_CLOTHES: 0x4169e1,
  SURVIVOR_GRAY_CLOTHES: 0x4a4a4a,
  SURVIVOR_WHITE_CLOTHES: 0xf5f5dc,
  SURVIVOR_WEAPON: 0x4a4a4a,
  SURVIVOR_RIFLE: 0x2a2a2a,
  SURVIVOR_ARMBAND: 0xcc0000,

  // Fog colors - cold green-gray banks
  FOG_DEEP: 0x5a6a5a,
  FOG_MID: 0x8a9a88,
  FOG_UPPER: 0xb8c8b8,
  FOG_LOWER: 0x7a8a78,

  // Animated decal colors
  DECAL_TREE_TRUNK: 0x4a3a2a,
  DECAL_TREE_FOLIAGE: 0x3a5a2a,
  DECAL_TREE_FOLIAGE_DARK: 0x2a4a1a,
  DECAL_POND_WATER: 0x2a4a5a,
  DECAL_POND_DEEP: 0x1a3a4a,
  DECAL_POND_SHIMMER: 0x6a9aaa,
  DECAL_POND_EDGE: 0x3a4a2a,
  DECAL_REED: 0x4a5a2a,
  DECAL_BIRD: 0x2a2a2a,
} as const;

// ============================================================================
// GRAVEYARD DIMENSIONS
// ============================================================================
export const GRAVEYARD = {
  X: 20,
  Y: 250,
  WIDTH: 140,
  HEIGHT: 280,
} as const;

// ============================================================================
// GROUND TEXTURE PARAMETERS
// ============================================================================
export const GROUND_TEXTURE = {
  // Large-scale mottling under patch layers
  MOTTLE_COUNT: 45,
  MOTTLE_MIN_SIZE: 50,
  MOTTLE_MAX_SIZE: 140,
  MOTTLE_MIN_ALPHA: 0.12,
  MOTTLE_MAX_ALPHA: 0.28,

  // Dirt/mud patches
  DIRT_PATCH_COUNT: 70,
  DIRT_PATCH_MIN_SIZE: 28,
  DIRT_PATCH_MAX_SIZE: 85,
  DIRT_PATCH_MIN_POINTS: 6,
  DIRT_PATCH_MAX_POINTS: 11,
  DIRT_PATCH_MIN_RADIUS_FACTOR: 0.6,
  DIRT_PATCH_MAX_RADIUS_FACTOR: 1.3,
  DIRT_PATCH_MIN_ALPHA: 0.35,
  DIRT_PATCH_MAX_ALPHA: 0.65,

  // Dead grass patches
  DEAD_GRASS_COUNT: 100,
  DEAD_GRASS_MIN_SIZE: 14,
  DEAD_GRASS_MAX_SIZE: 42,
  DEAD_GRASS_MIN_POINTS: 5,
  DEAD_GRASS_MAX_POINTS: 9,
  DEAD_GRASS_MIN_RADIUS_FACTOR: 0.7,
  DEAD_GRASS_MAX_RADIUS_FACTOR: 1.2,
  DEAD_GRASS_MIN_ALPHA: 0.18,
  DEAD_GRASS_MAX_ALPHA: 0.38,

  // Barren dirt patches
  BARREN_DIRT_COUNT: 55,
  BARREN_DIRT_MIN_SIZE: 22,
  BARREN_DIRT_MAX_SIZE: 65,
  BARREN_DIRT_MIN_POINTS: 4,
  BARREN_DIRT_MAX_POINTS: 8,
  BARREN_DIRT_MIN_RADIUS_FACTOR: 0.5,
  BARREN_DIRT_MAX_RADIUS_FACTOR: 1.3,
  BARREN_DIRT_MIN_ALPHA: 0.28,
  BARREN_DIRT_MAX_ALPHA: 0.55,

  // Mud / damp earth
  MUD_COUNT: 35,
  MUD_MIN_SIZE: 18,
  MUD_MAX_SIZE: 48,
  MUD_MIN_ALPHA: 0.2,
  MUD_MAX_ALPHA: 0.4,

  // Ash / scorched patches
  ASH_COUNT: 20,
  ASH_MIN_SIZE: 16,
  ASH_MAX_SIZE: 40,
  ASH_MIN_ALPHA: 0.15,
  ASH_MAX_ALPHA: 0.32,

  // Rocks and debris
  ROCK_COUNT: 55,
  ROCK_MIN_SIZE: 3,
  ROCK_MAX_SIZE: 14,
  ROCK_MIN_POINTS: 3,
  ROCK_MAX_POINTS: 7,
  ROCK_MIN_RADIUS_FACTOR: 0.7,
  ROCK_MAX_RADIUS_FACTOR: 1.2,
  ROCK_MIN_ALPHA: 0.45,
  ROCK_MAX_ALPHA: 0.85,

  // Pebbles
  PEBBLE_COUNT: 110,
  PEBBLE_MIN_SIZE: 1,
  PEBBLE_MAX_SIZE: 3.5,
  PEBBLE_MIN_ALPHA: 0.45,
  PEBBLE_MAX_ALPHA: 0.8,

  // Ground cracks
  CRACK_COUNT: 40,
  CRACK_MIN_LENGTH: 35,
  CRACK_MAX_LENGTH: 120,
  CRACK_MIN_SEGMENTS: 4,
  CRACK_MAX_SEGMENTS: 9,
  CRACK_ANGLE_VARIATION: 0.65,
  CRACK_MIN_WIDTH: 1.2,
  CRACK_MAX_WIDTH: 2.4,
  CRACK_ALPHA: 0.55,
  CRACK_BRANCH_PROBABILITY: 0.45,
  CRACK_BRANCH_MIN_LENGTH_FACTOR: 0.3,
  CRACK_BRANCH_MAX_LENGTH_FACTOR: 0.7,
  CRACK_BRANCH_WIDTH: 1,
  CRACK_BRANCH_ALPHA: 0.4,

  // Weathering stains
  STAIN_COUNT: 45,
  STAIN_MIN_SIZE: 18,
  STAIN_MAX_SIZE: 55,
  STAIN_MIN_ALPHA: 0.12,
  STAIN_MAX_ALPHA: 0.28,

  // Grass tufts
  GRASS_TUFT_COUNT: 160,
  GRASS_TUFT_MIN_SIZE: 2,
  GRASS_TUFT_MAX_SIZE: 6,
  GRASS_TUFT_MIN_POINTS: 3,
  GRASS_TUFT_MAX_POINTS: 6,
  GRASS_TUFT_MIN_RADIUS_FACTOR: 0.8,
  GRASS_TUFT_MAX_RADIUS_FACTOR: 1.2,
  GRASS_TUFT_MIN_ALPHA: 0.3,
  GRASS_TUFT_MAX_ALPHA: 0.55,
  GRASS_BLADE_COUNT: 3,
} as const;

// ============================================================================
// UI DIMENSIONS
// ============================================================================
export const UI_DIMENSIONS = {
  PLAY_AREA_WIDTH: 1024,
  PANEL_WIDTH: 256,
  TOTAL_WIDTH: 1280,
  HEIGHT: 768,
  SEPARATOR_WIDTH: 4,
} as const;

// ============================================================================
// PATH PARAMETERS
// ============================================================================
export const PATH = {
  WIDTH: 50,
  CORNER_RADIUS: 30,
  SHOULDER_WIDTH: 14, // soft blend beyond outer border
  SHOULDER_ALPHA: 0.22,
  OUTER_BORDER_WIDTH: 10,
  SURFACE_LIGHT_FACTOR: 0.82, // secondary lighter fill
  SURFACE_LIGHT_ALPHA: 0.35,
  INNER_WIDTH_FACTOR: 0.55,
  INNER_ALPHA: 0.55,
  TRACK_OFFSET_FACTOR: 0.22,
  TRACK_WIDTH: 2.5,
  TRACK_ALPHA: 0.55,
  TRACK_WOBBLE: 1.8,
  DIRT_STEP_SIZE: 12,
  // Spawn chances (0–1)
  DIRT_PATCH_CHANCE: 0.55,
  DIRT_PATCH_MIN_SIZE: 2.5,
  DIRT_PATCH_MAX_SIZE: 7,
  DIRT_PATCH_OFFSET_FACTOR: 0.55,
  DIRT_PATCH_MIN_ALPHA: 0.2,
  DIRT_PATCH_MAX_ALPHA: 0.45,
  ROCK_CHANCE: 0.18,
  ROCK_MIN_SIZE: 1.5,
  ROCK_MAX_SIZE: 4,
  ROCK_OFFSET_FACTOR: 0.48,
  ROCK_MIN_ALPHA: 0.5,
  ROCK_MAX_ALPHA: 0.85,
  FOOTPRINT_CHANCE: 0.14,
  FOOTPRINT_OFFSET_FACTOR: 0.35,
  FOOTPRINT_WIDTH: 2.2,
  FOOTPRINT_HEIGHT: 4.5,
  FOOTPRINT_MIN_ALPHA: 0.18,
  FOOTPRINT_MAX_ALPHA: 0.35,
  MUD_CHANCE: 0.12,
  MUD_MIN_RX: 4,
  MUD_MAX_RX: 10,
  MUD_ALPHA: 0.28,
  CRACK_CHANCE: 0.08,
  CRACK_LENGTH: 10,
  EDGE_BLOB_CHANCE: 0.35,
  EDGE_BLOB_SIZE: 4,
  EDGE_BLOB_ALPHA: 0.3,
  HIGHLIGHT_BORDER_WIDTH: 3,
  HIGHLIGHT_ALPHA: 0.18,
} as const;

// ============================================================================
// GRAVEYARD DETAILS
// ============================================================================
export const GRAVEYARD_DETAILS = {
  // Position
  X: 20,
  Y: 250,
  WIDTH: 140,
  HEIGHT: 280,

  // Dead grass patches
  DEAD_GRASS_COUNT: 30,
  DEAD_GRASS_MIN_SIZE: 8,
  DEAD_GRASS_MAX_SIZE: 23, // 8 + 15
  DEAD_GRASS_MIN_POINTS: 5,
  DEAD_GRASS_MAX_POINTS: 8, // 5 + 3
  DEAD_GRASS_MIN_RADIUS_FACTOR: 0.6,
  DEAD_GRASS_MAX_RADIUS_FACTOR: 1.2, // 0.6 + 0.6
  DEAD_GRASS_MIN_ALPHA: 0.4,
  DEAD_GRASS_MAX_ALPHA: 0.7, // 0.4 + 0.3
  DEAD_GRASS_COLOR: 0x2a3a2a,

  // Disturbed earth
  DISTURBED_EARTH_COUNT: 20,
  DISTURBED_EARTH_MIN_SIZE: 10,
  DISTURBED_EARTH_MAX_SIZE: 30, // 10 + 20
  DISTURBED_EARTH_MIN_POINTS: 4,
  DISTURBED_EARTH_MAX_POINTS: 7, // 4 + 3
  DISTURBED_EARTH_MIN_RADIUS_FACTOR: 0.5,
  DISTURBED_EARTH_MAX_RADIUS_FACTOR: 1.2, // 0.5 + 0.7
  DISTURBED_EARTH_MIN_ALPHA: 0.5,
  DISTURBED_EARTH_MAX_ALPHA: 0.8, // 0.5 + 0.3
  DISTURBED_EARTH_COLOR: 0x4a3a2a,

  // Bones
  BONES_COUNT: 25,
  BONES_MIN_SIZE: 2,
  BONES_MAX_SIZE: 6, // 2 + 4
  BONES_HEIGHT_FACTOR: 2,
  BONES_MIN_ALPHA: 0.6,
  BONES_MAX_ALPHA: 0.9, // 0.6 + 0.3
  BONES_COLOR: 0xf5f5dc,

  // Stains
  STAINS_COUNT: 15,
  STAINS_MIN_SIZE: 8,
  STAINS_MAX_SIZE: 23, // 8 + 15
  STAINS_MIN_ALPHA: 0.3,
  STAINS_MAX_ALPHA: 0.5, // 0.3 + 0.2
  STAINS_COLOR: 0x1a1a1a,

  // Ground
  GROUND_COLOR: 0x1a2a1a,

  // Fence (wrought iron with spiked bars)
  FENCE_THICKNESS: 4,
  FENCE_BAR_SPACING: 9,
  FENCE_BAR_WIDTH: 2,
  FENCE_SPIKE_HEIGHT: 5,
  FENCE_RAIL_THICKNESS: 3,
  FENCE_RUST_SPOTS: 8,
  FENCE_RUST_SIZE: 2,
  FENCE_RUST_ALPHA: 0.7,
  FENCE_POST_SPACING: 35,
  FENCE_POST_WIDTH: 9,
  FENCE_POST_HEIGHT: 7,
  FENCE_RUST_STREAKS: 5,
  FENCE_RUST_STREAK_LENGTH: 20,
  FENCE_RUST_STREAK_ALPHA: 0.5,
  FENCE_COLOR: 0x4a3a2a,
  FENCE_BORDER_COLOR: 0x2a1a12,
  FENCE_BAR_COLOR: 0x5a4a3a,
  FENCE_POST_COLOR: 0x5a4321,
  FENCE_POST_BORDER_COLOR: 0x3a2a11,
  WOOD_GRAIN_COLOR: 0x4a3211,
  RUST_COLOR: 0x8b4513,
  RUST_ALPHA: 0.7,
  PATH_COLOR: 0x2a2218,
  PATH_EDGE_COLOR: 0x3a2a1a,

  // Gate
  GATE_X_OFFSET: 50,
  GATE_Y: 360,
  GATE_WIDTH: 50,
  GATE_HEIGHT: 60,
  GATE_PILLAR_WIDTH: 8,
  GATE_PILLAR_COLOR: 0x5a5a5a,
  GATE_PILLAR_BORDER_COLOR: 0x3a3a3a,
  GATE_CRACK_COLOR: 0x2a2a2a,
  GATE_CRACK_ALPHA: 0.7,
  GATE_MOSS_SPOTS: 3,
  GATE_MOSS_COLOR: 0x2a4a2a,
  GATE_MOSS_ALPHA: 0.6,
  GATE_IRON_COLOR: 0x5a4a3a,
  GATE_IRON_ALPHA: 0.9,
  GATE_IRON_BORDER_COLOR: 0x3a2a1a,
  GATE_RUST_SPOTS: 4,
  GATE_RUST_ALPHA: 0.8,
  GATE_BAR_COUNT: 3,
  GATE_SIGN_WIDTH: 30,
  GATE_SIGN_HEIGHT: 12,
  GATE_SIGN_COLOR: 0x3a2a1a,
  GATE_SIGN_BORDER_COLOR: 0x2a1a0a,
  GATE_SIGN_CRACK_COLOR: 0x1a0a0a,
  CHAIN_COLOR: 0x5a4a3a,
  CHAIN_LINK_COUNT: 3,

  // Skulls
  SKULL_SIZE: 5,
  SKULL_COLOR: 0xe5e5cc,
  SKULL_BORDER_COLOR: 0xc5c5ac,
  SKULL_EYE_COLOR: 0x1a1a1a,

  // Gravestones
  CROSS_COLOR: 0x4a3a2a,
  CROSS_BORDER_COLOR: 0x2a1a1a,
  HEADSTONE_COLOR: 0x5a5a5a,
  HEADSTONE_BORDER_COLOR: 0x3a3a3a,
  HEADSTONE_CRACK_COLOR: 0x2a2a2a,
  MONUMENT_BASE_COLOR: 0x6a6a6a,
  MONUMENT_BASE_BORDER_COLOR: 0x4a4a4a,
  SHADOW_COLOR: 0x000000,
  SHADOW_ALPHA: 0.3,

  // Dead trees
  DEAD_TREE_TRUNK_COLOR: 0x4a3a2a,
  DEAD_TREE_TRUNK_BORDER_COLOR: 0x2a1a1a,

  // Eerie glow (sickly olive, not neon)
  GLOW_SPOT_COUNT: 6,
  GLOW_MIN_SIZE: 10,
  GLOW_MAX_SIZE: 18,
  GLOW_COLOR: 0x3a6a3a,
  GLOW_ALPHA: 0.1,
  OPEN_GRAVE_GLOW_COLOR: 0x2a4a2a,
  OPEN_GRAVE_GLOW_ALPHA: 0.18,

  // Open graves
  OPEN_GRAVE_HOLE_COLOR: 0x1a1a1a,
  OPEN_GRAVE_BORDER_COLOR: 0x2a2a2a,
  OPEN_GRAVE_DIRT_COLOR: 0x654321,
  COFFIN_COLOR: 0x4a3a2a,
} as const;

// ============================================================================
// FOG PARAMETERS
// ============================================================================
export const FOG = {
  // Deep bank (slow, dense, lower graveyard)
  DEEP_COUNT: 8,
  DEEP_Y_MIN: 0.45,
  DEEP_Y_MAX: 0.95,
  DEEP_MIN_RX: 28,
  DEEP_MAX_RX: 48,
  DEEP_MIN_RY: 12,
  DEEP_MAX_RY: 22,
  DEEP_MIN_SPEED: 0.12,
  DEEP_MAX_SPEED: 0.28,
  DEEP_MIN_ALPHA: 0.1,
  DEEP_MAX_ALPHA: 0.18,
  DEEP_DRIFT: 10,

  // Mid haze (fills most of the plot)
  MID_COUNT: 14,
  MID_Y_MIN: 0.08,
  MID_Y_MAX: 0.85,
  MID_MIN_RX: 20,
  MID_MAX_RX: 38,
  MID_MIN_RY: 9,
  MID_MAX_RY: 18,
  MID_MIN_SPEED: 0.22,
  MID_MAX_SPEED: 0.45,
  MID_MIN_ALPHA: 0.08,
  MID_MAX_ALPHA: 0.16,
  MID_DRIFT: 18,

  // Upper wisps (lighter, faster)
  UPPER_COUNT: 12,
  UPPER_Y_MIN: 0.0,
  UPPER_Y_MAX: 0.55,
  UPPER_MIN_RX: 14,
  UPPER_MAX_RX: 28,
  UPPER_MIN_RY: 6,
  UPPER_MAX_RY: 14,
  UPPER_MIN_SPEED: 0.35,
  UPPER_MAX_SPEED: 0.7,
  UPPER_MIN_ALPHA: 0.06,
  UPPER_MAX_ALPHA: 0.13,
  UPPER_DRIFT: 24,

  // Soft spill outside graveyard bounds
  SPILL_X: 18,
  SPILL_Y: 12,

  // Animation
  BOB_AMPLITUDE: 4,
  BOB_SPEED_FACTOR: 0.45,
  PULSE_SPEED: 0.4,
  PULSE_MIN_FACTOR: 0.65,
  PULSE_MAX_FACTOR: 1.0,
  RING_COUNT: 3,
  RING_ALPHA_FALLOFF: 0.45,
} as const;

// ============================================================================
// ANIMATED MAP DECALS
// ============================================================================
export const DECALS = {
  PATH_CLEARANCE: 55,
  MIN_Y: 160,

  // Swaying leafy trees
  TREE_COUNT: 7,
  TREE_MIN_HEIGHT: 28,
  TREE_MAX_HEIGHT: 44,
  TREE_SWAY_AMPLITUDE: 3.5,
  TREE_SWAY_SPEED: 1.1,

  // Ponds
  POND_COUNT: 2,
  POND_MIN_RX: 28,
  POND_MAX_RX: 42,
  POND_MIN_RY: 14,
  POND_MAX_RY: 22,
  POND_SHIMMER_COUNT: 4,
  POND_SHIMMER_SPEED: 1.4,

  // Reeds near ponds
  REED_PER_POND: 5,
  REED_MIN_HEIGHT: 10,
  REED_MAX_HEIGHT: 18,
  REED_SWAY_AMPLITUDE: 2.5,
  REED_SWAY_SPEED: 1.6,

  // Birds
  BIRD_COUNT: 6,
  BIRD_MIN_SPEED: 18,
  BIRD_MAX_SPEED: 36,
  BIRD_MIN_SIZE: 3,
  BIRD_MAX_SIZE: 5,
  BIRD_BOB_AMPLITUDE: 8,
  BIRD_BOB_SPEED: 1.2,
  BIRD_WING_SPEED: 8,
  BIRD_MIN_Y: 40,
  BIRD_MAX_Y: 220,
} as const;
